

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: camagru_web
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db
      - mailhog
    env_file:
      - .env
    networks:
      - camagru_network

  db:
    image: postgres:14
    container_name: camagru_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - camagru_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: camagru_pgadmin
    ports:
      - "8888:80"
    env_file:
      - .env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - camagru_network

  mailhog:
    image: mailhog/mailhog
    container_name: camagru_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - camagru_network

volumes:
  db_data:
  pgadmin_data:

networks:
  camagru_network:
    driver: bridge
